/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables.records;


import brs.schema.tables.Asset;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetRecord extends UpdatableRecordImpl<AssetRecord> implements Record9<Long, Long, Long, String, String, Long, Byte, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB.asset.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.asset.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.asset.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.asset.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.asset.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.asset.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DB.asset.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.asset.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB.asset.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.asset.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB.asset.quantity</code>.
     */
    public void setQuantity(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.asset.quantity</code>.
     */
    public Long getQuantity() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>DB.asset.decimals</code>.
     */
    public void setDecimals(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>DB.asset.decimals</code>.
     */
    public Byte getDecimals() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>DB.asset.height</code>.
     */
    public void setHeight(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>DB.asset.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>DB.asset.mintable</code>.
     */
    public void setMintable(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>DB.asset.mintable</code>.
     */
    public Boolean getMintable() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, String, String, Long, Byte, Integer, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Long, String, String, Long, Byte, Integer, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Asset.ASSET.DB_ID;
    }

    @Override
    public Field<Long> field2() {
        return Asset.ASSET.ID;
    }

    @Override
    public Field<Long> field3() {
        return Asset.ASSET.ACCOUNT_ID;
    }

    @Override
    public Field<String> field4() {
        return Asset.ASSET.NAME;
    }

    @Override
    public Field<String> field5() {
        return Asset.ASSET.DESCRIPTION;
    }

    @Override
    public Field<Long> field6() {
        return Asset.ASSET.QUANTITY;
    }

    @Override
    public Field<Byte> field7() {
        return Asset.ASSET.DECIMALS;
    }

    @Override
    public Field<Integer> field8() {
        return Asset.ASSET.HEIGHT;
    }

    @Override
    public Field<Boolean> field9() {
        return Asset.ASSET.MINTABLE;
    }

    @Override
    public Long component1() {
        return getDbId();
    }

    @Override
    public Long component2() {
        return getId();
    }

    @Override
    public Long component3() {
        return getAccountId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Long component6() {
        return getQuantity();
    }

    @Override
    public Byte component7() {
        return getDecimals();
    }

    @Override
    public Integer component8() {
        return getHeight();
    }

    @Override
    public Boolean component9() {
        return getMintable();
    }

    @Override
    public Long value1() {
        return getDbId();
    }

    @Override
    public Long value2() {
        return getId();
    }

    @Override
    public Long value3() {
        return getAccountId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Long value6() {
        return getQuantity();
    }

    @Override
    public Byte value7() {
        return getDecimals();
    }

    @Override
    public Integer value8() {
        return getHeight();
    }

    @Override
    public Boolean value9() {
        return getMintable();
    }

    @Override
    public AssetRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    @Override
    public AssetRecord value2(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AssetRecord value3(Long value) {
        setAccountId(value);
        return this;
    }

    @Override
    public AssetRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public AssetRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AssetRecord value6(Long value) {
        setQuantity(value);
        return this;
    }

    @Override
    public AssetRecord value7(Byte value) {
        setDecimals(value);
        return this;
    }

    @Override
    public AssetRecord value8(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public AssetRecord value9(Boolean value) {
        setMintable(value);
        return this;
    }

    @Override
    public AssetRecord values(Long value1, Long value2, Long value3, String value4, String value5, Long value6, Byte value7, Integer value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetRecord
     */
    public AssetRecord() {
        super(Asset.ASSET);
    }

    /**
     * Create a detached, initialised AssetRecord
     */
    public AssetRecord(Long dbId, Long id, Long accountId, String name, String description, Long quantity, Byte decimals, Integer height, Boolean mintable) {
        super(Asset.ASSET);

        setDbId(dbId);
        setId(id);
        setAccountId(accountId);
        setName(name);
        setDescription(description);
        setQuantity(quantity);
        setDecimals(decimals);
        setHeight(height);
        setMintable(mintable);
    }
}
