/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables.records;


import brs.schema.tables.AtMap;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtMapRecord extends UpdatableRecordImpl<AtMapRecord> implements Record7<Long, Long, Long, Long, Long, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB.at_map.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.at_map.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.at_map.at_id</code>.
     */
    public void setAtId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.at_map.at_id</code>.
     */
    public Long getAtId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.at_map.key1</code>.
     */
    public void setKey1(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.at_map.key1</code>.
     */
    public Long getKey1() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DB.at_map.key2</code>.
     */
    public void setKey2(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.at_map.key2</code>.
     */
    public Long getKey2() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>DB.at_map.value</code>.
     */
    public void setValue(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.at_map.value</code>.
     */
    public Long getValue() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DB.at_map.height</code>.
     */
    public void setHeight(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.at_map.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>DB.at_map.latest</code>.
     */
    public void setLatest(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>DB.at_map.latest</code>.
     */
    public Boolean getLatest() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, Long, Integer, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AtMap.AT_MAP.DB_ID;
    }

    @Override
    public Field<Long> field2() {
        return AtMap.AT_MAP.AT_ID;
    }

    @Override
    public Field<Long> field3() {
        return AtMap.AT_MAP.KEY1;
    }

    @Override
    public Field<Long> field4() {
        return AtMap.AT_MAP.KEY2;
    }

    @Override
    public Field<Long> field5() {
        return AtMap.AT_MAP.VALUE;
    }

    @Override
    public Field<Integer> field6() {
        return AtMap.AT_MAP.HEIGHT;
    }

    @Override
    public Field<Boolean> field7() {
        return AtMap.AT_MAP.LATEST;
    }

    @Override
    public Long component1() {
        return getDbId();
    }

    @Override
    public Long component2() {
        return getAtId();
    }

    @Override
    public Long component3() {
        return getKey1();
    }

    @Override
    public Long component4() {
        return getKey2();
    }

    @Override
    public Long component5() {
        return getValue();
    }

    @Override
    public Integer component6() {
        return getHeight();
    }

    @Override
    public Boolean component7() {
        return getLatest();
    }

    @Override
    public Long value1() {
        return getDbId();
    }

    @Override
    public Long value2() {
        return getAtId();
    }

    @Override
    public Long value3() {
        return getKey1();
    }

    @Override
    public Long value4() {
        return getKey2();
    }

    @Override
    public Long value5() {
        return getValue();
    }

    @Override
    public Integer value6() {
        return getHeight();
    }

    @Override
    public Boolean value7() {
        return getLatest();
    }

    @Override
    public AtMapRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    @Override
    public AtMapRecord value2(Long value) {
        setAtId(value);
        return this;
    }

    @Override
    public AtMapRecord value3(Long value) {
        setKey1(value);
        return this;
    }

    @Override
    public AtMapRecord value4(Long value) {
        setKey2(value);
        return this;
    }

    @Override
    public AtMapRecord value5(Long value) {
        setValue(value);
        return this;
    }

    @Override
    public AtMapRecord value6(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public AtMapRecord value7(Boolean value) {
        setLatest(value);
        return this;
    }

    @Override
    public AtMapRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Integer value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AtMapRecord
     */
    public AtMapRecord() {
        super(AtMap.AT_MAP);
    }

    /**
     * Create a detached, initialised AtMapRecord
     */
    public AtMapRecord(Long dbId, Long atId, Long key1, Long key2, Long value, Integer height, Boolean latest) {
        super(AtMap.AT_MAP);

        setDbId(dbId);
        setAtId(atId);
        setKey1(key1);
        setKey2(key2);
        setValue(value);
        setHeight(height);
        setLatest(latest);
    }
}
