/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables.records;


import brs.schema.tables.Block;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlockRecord extends UpdatableRecordImpl<BlockRecord> implements Record22<Long, Long, Integer, Integer, Long, Long, Long, Integer, byte[], byte[], byte[], Long, Long, Integer, byte[], byte[], byte[], Long, Long, byte[], Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB.block.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.block.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.block.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.block.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.block.version</code>.
     */
    public void setVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.block.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DB.block.timestamp</code>.
     */
    public void setTimestamp(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.block.timestamp</code>.
     */
    public Integer getTimestamp() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DB.block.previous_block_id</code>.
     */
    public void setPreviousBlockId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.block.previous_block_id</code>.
     */
    public Long getPreviousBlockId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DB.block.total_amount</code>.
     */
    public void setTotalAmount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.block.total_amount</code>.
     */
    public Long getTotalAmount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>DB.block.total_fee</code>.
     */
    public void setTotalFee(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>DB.block.total_fee</code>.
     */
    public Long getTotalFee() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>DB.block.payload_length</code>.
     */
    public void setPayloadLength(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>DB.block.payload_length</code>.
     */
    public Integer getPayloadLength() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>DB.block.generator_public_key</code>.
     */
    public void setGeneratorPublicKey(byte[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>DB.block.generator_public_key</code>.
     */
    public byte[] getGeneratorPublicKey() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>DB.block.previous_block_hash</code>.
     */
    public void setPreviousBlockHash(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>DB.block.previous_block_hash</code>.
     */
    public byte[] getPreviousBlockHash() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>DB.block.cumulative_difficulty</code>.
     */
    public void setCumulativeDifficulty(byte[] value) {
        set(10, value);
    }

    /**
     * Getter for <code>DB.block.cumulative_difficulty</code>.
     */
    public byte[] getCumulativeDifficulty() {
        return (byte[]) get(10);
    }

    /**
     * Setter for <code>DB.block.base_target</code>.
     */
    public void setBaseTarget(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>DB.block.base_target</code>.
     */
    public Long getBaseTarget() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>DB.block.next_block_id</code>.
     */
    public void setNextBlockId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>DB.block.next_block_id</code>.
     */
    public Long getNextBlockId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>DB.block.height</code>.
     */
    public void setHeight(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>DB.block.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>DB.block.generation_signature</code>.
     */
    public void setGenerationSignature(byte[] value) {
        set(14, value);
    }

    /**
     * Getter for <code>DB.block.generation_signature</code>.
     */
    public byte[] getGenerationSignature() {
        return (byte[]) get(14);
    }

    /**
     * Setter for <code>DB.block.block_signature</code>.
     */
    public void setBlockSignature(byte[] value) {
        set(15, value);
    }

    /**
     * Getter for <code>DB.block.block_signature</code>.
     */
    public byte[] getBlockSignature() {
        return (byte[]) get(15);
    }

    /**
     * Setter for <code>DB.block.payload_hash</code>.
     */
    public void setPayloadHash(byte[] value) {
        set(16, value);
    }

    /**
     * Getter for <code>DB.block.payload_hash</code>.
     */
    public byte[] getPayloadHash() {
        return (byte[]) get(16);
    }

    /**
     * Setter for <code>DB.block.generator_id</code>.
     */
    public void setGeneratorId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>DB.block.generator_id</code>.
     */
    public Long getGeneratorId() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>DB.block.nonce</code>.
     */
    public void setNonce(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>DB.block.nonce</code>.
     */
    public Long getNonce() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>DB.block.ats</code>.
     */
    public void setAts(byte[] value) {
        set(19, value);
    }

    /**
     * Getter for <code>DB.block.ats</code>.
     */
    public byte[] getAts() {
        return (byte[]) get(19);
    }

    /**
     * Setter for <code>DB.block.total_fee_cash_back</code>.
     */
    public void setTotalFeeCashBack(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>DB.block.total_fee_cash_back</code>.
     */
    public Long getTotalFeeCashBack() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>DB.block.total_fee_burnt</code>.
     */
    public void setTotalFeeBurnt(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>DB.block.total_fee_burnt</code>.
     */
    public Long getTotalFeeBurnt() {
        return (Long) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, Long, Integer, Integer, Long, Long, Long, Integer, byte[], byte[], byte[], Long, Long, Integer, byte[], byte[], byte[], Long, Long, byte[], Long, Long> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<Long, Long, Integer, Integer, Long, Long, Long, Integer, byte[], byte[], byte[], Long, Long, Integer, byte[], byte[], byte[], Long, Long, byte[], Long, Long> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Block.BLOCK.DB_ID;
    }

    @Override
    public Field<Long> field2() {
        return Block.BLOCK.ID;
    }

    @Override
    public Field<Integer> field3() {
        return Block.BLOCK.VERSION;
    }

    @Override
    public Field<Integer> field4() {
        return Block.BLOCK.TIMESTAMP;
    }

    @Override
    public Field<Long> field5() {
        return Block.BLOCK.PREVIOUS_BLOCK_ID;
    }

    @Override
    public Field<Long> field6() {
        return Block.BLOCK.TOTAL_AMOUNT;
    }

    @Override
    public Field<Long> field7() {
        return Block.BLOCK.TOTAL_FEE;
    }

    @Override
    public Field<Integer> field8() {
        return Block.BLOCK.PAYLOAD_LENGTH;
    }

    @Override
    public Field<byte[]> field9() {
        return Block.BLOCK.GENERATOR_PUBLIC_KEY;
    }

    @Override
    public Field<byte[]> field10() {
        return Block.BLOCK.PREVIOUS_BLOCK_HASH;
    }

    @Override
    public Field<byte[]> field11() {
        return Block.BLOCK.CUMULATIVE_DIFFICULTY;
    }

    @Override
    public Field<Long> field12() {
        return Block.BLOCK.BASE_TARGET;
    }

    @Override
    public Field<Long> field13() {
        return Block.BLOCK.NEXT_BLOCK_ID;
    }

    @Override
    public Field<Integer> field14() {
        return Block.BLOCK.HEIGHT;
    }

    @Override
    public Field<byte[]> field15() {
        return Block.BLOCK.GENERATION_SIGNATURE;
    }

    @Override
    public Field<byte[]> field16() {
        return Block.BLOCK.BLOCK_SIGNATURE;
    }

    @Override
    public Field<byte[]> field17() {
        return Block.BLOCK.PAYLOAD_HASH;
    }

    @Override
    public Field<Long> field18() {
        return Block.BLOCK.GENERATOR_ID;
    }

    @Override
    public Field<Long> field19() {
        return Block.BLOCK.NONCE;
    }

    @Override
    public Field<byte[]> field20() {
        return Block.BLOCK.ATS;
    }

    @Override
    public Field<Long> field21() {
        return Block.BLOCK.TOTAL_FEE_CASH_BACK;
    }

    @Override
    public Field<Long> field22() {
        return Block.BLOCK.TOTAL_FEE_BURNT;
    }

    @Override
    public Long component1() {
        return getDbId();
    }

    @Override
    public Long component2() {
        return getId();
    }

    @Override
    public Integer component3() {
        return getVersion();
    }

    @Override
    public Integer component4() {
        return getTimestamp();
    }

    @Override
    public Long component5() {
        return getPreviousBlockId();
    }

    @Override
    public Long component6() {
        return getTotalAmount();
    }

    @Override
    public Long component7() {
        return getTotalFee();
    }

    @Override
    public Integer component8() {
        return getPayloadLength();
    }

    @Override
    public byte[] component9() {
        return getGeneratorPublicKey();
    }

    @Override
    public byte[] component10() {
        return getPreviousBlockHash();
    }

    @Override
    public byte[] component11() {
        return getCumulativeDifficulty();
    }

    @Override
    public Long component12() {
        return getBaseTarget();
    }

    @Override
    public Long component13() {
        return getNextBlockId();
    }

    @Override
    public Integer component14() {
        return getHeight();
    }

    @Override
    public byte[] component15() {
        return getGenerationSignature();
    }

    @Override
    public byte[] component16() {
        return getBlockSignature();
    }

    @Override
    public byte[] component17() {
        return getPayloadHash();
    }

    @Override
    public Long component18() {
        return getGeneratorId();
    }

    @Override
    public Long component19() {
        return getNonce();
    }

    @Override
    public byte[] component20() {
        return getAts();
    }

    @Override
    public Long component21() {
        return getTotalFeeCashBack();
    }

    @Override
    public Long component22() {
        return getTotalFeeBurnt();
    }

    @Override
    public Long value1() {
        return getDbId();
    }

    @Override
    public Long value2() {
        return getId();
    }

    @Override
    public Integer value3() {
        return getVersion();
    }

    @Override
    public Integer value4() {
        return getTimestamp();
    }

    @Override
    public Long value5() {
        return getPreviousBlockId();
    }

    @Override
    public Long value6() {
        return getTotalAmount();
    }

    @Override
    public Long value7() {
        return getTotalFee();
    }

    @Override
    public Integer value8() {
        return getPayloadLength();
    }

    @Override
    public byte[] value9() {
        return getGeneratorPublicKey();
    }

    @Override
    public byte[] value10() {
        return getPreviousBlockHash();
    }

    @Override
    public byte[] value11() {
        return getCumulativeDifficulty();
    }

    @Override
    public Long value12() {
        return getBaseTarget();
    }

    @Override
    public Long value13() {
        return getNextBlockId();
    }

    @Override
    public Integer value14() {
        return getHeight();
    }

    @Override
    public byte[] value15() {
        return getGenerationSignature();
    }

    @Override
    public byte[] value16() {
        return getBlockSignature();
    }

    @Override
    public byte[] value17() {
        return getPayloadHash();
    }

    @Override
    public Long value18() {
        return getGeneratorId();
    }

    @Override
    public Long value19() {
        return getNonce();
    }

    @Override
    public byte[] value20() {
        return getAts();
    }

    @Override
    public Long value21() {
        return getTotalFeeCashBack();
    }

    @Override
    public Long value22() {
        return getTotalFeeBurnt();
    }

    @Override
    public BlockRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    @Override
    public BlockRecord value2(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BlockRecord value3(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public BlockRecord value4(Integer value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public BlockRecord value5(Long value) {
        setPreviousBlockId(value);
        return this;
    }

    @Override
    public BlockRecord value6(Long value) {
        setTotalAmount(value);
        return this;
    }

    @Override
    public BlockRecord value7(Long value) {
        setTotalFee(value);
        return this;
    }

    @Override
    public BlockRecord value8(Integer value) {
        setPayloadLength(value);
        return this;
    }

    @Override
    public BlockRecord value9(byte[] value) {
        setGeneratorPublicKey(value);
        return this;
    }

    @Override
    public BlockRecord value10(byte[] value) {
        setPreviousBlockHash(value);
        return this;
    }

    @Override
    public BlockRecord value11(byte[] value) {
        setCumulativeDifficulty(value);
        return this;
    }

    @Override
    public BlockRecord value12(Long value) {
        setBaseTarget(value);
        return this;
    }

    @Override
    public BlockRecord value13(Long value) {
        setNextBlockId(value);
        return this;
    }

    @Override
    public BlockRecord value14(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public BlockRecord value15(byte[] value) {
        setGenerationSignature(value);
        return this;
    }

    @Override
    public BlockRecord value16(byte[] value) {
        setBlockSignature(value);
        return this;
    }

    @Override
    public BlockRecord value17(byte[] value) {
        setPayloadHash(value);
        return this;
    }

    @Override
    public BlockRecord value18(Long value) {
        setGeneratorId(value);
        return this;
    }

    @Override
    public BlockRecord value19(Long value) {
        setNonce(value);
        return this;
    }

    @Override
    public BlockRecord value20(byte[] value) {
        setAts(value);
        return this;
    }

    @Override
    public BlockRecord value21(Long value) {
        setTotalFeeCashBack(value);
        return this;
    }

    @Override
    public BlockRecord value22(Long value) {
        setTotalFeeBurnt(value);
        return this;
    }

    @Override
    public BlockRecord values(Long value1, Long value2, Integer value3, Integer value4, Long value5, Long value6, Long value7, Integer value8, byte[] value9, byte[] value10, byte[] value11, Long value12, Long value13, Integer value14, byte[] value15, byte[] value16, byte[] value17, Long value18, Long value19, byte[] value20, Long value21, Long value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlockRecord
     */
    public BlockRecord() {
        super(Block.BLOCK);
    }

    /**
     * Create a detached, initialised BlockRecord
     */
    public BlockRecord(Long dbId, Long id, Integer version, Integer timestamp, Long previousBlockId, Long totalAmount, Long totalFee, Integer payloadLength, byte[] generatorPublicKey, byte[] previousBlockHash, byte[] cumulativeDifficulty, Long baseTarget, Long nextBlockId, Integer height, byte[] generationSignature, byte[] blockSignature, byte[] payloadHash, Long generatorId, Long nonce, byte[] ats, Long totalFeeCashBack, Long totalFeeBurnt) {
        super(Block.BLOCK);

        setDbId(dbId);
        setId(id);
        setVersion(version);
        setTimestamp(timestamp);
        setPreviousBlockId(previousBlockId);
        setTotalAmount(totalAmount);
        setTotalFee(totalFee);
        setPayloadLength(payloadLength);
        setGeneratorPublicKey(generatorPublicKey);
        setPreviousBlockHash(previousBlockHash);
        setCumulativeDifficulty(cumulativeDifficulty);
        setBaseTarget(baseTarget);
        setNextBlockId(nextBlockId);
        setHeight(height);
        setGenerationSignature(generationSignature);
        setBlockSignature(blockSignature);
        setPayloadHash(payloadHash);
        setGeneratorId(generatorId);
        setNonce(nonce);
        setAts(ats);
        setTotalFeeCashBack(totalFeeCashBack);
        setTotalFeeBurnt(totalFeeBurnt);
    }
}
