/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Keys;
import brs.schema.tables.records.AliasOfferRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AliasOffer extends TableImpl<AliasOfferRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.alias_offer</code>
     */
    public static final AliasOffer ALIAS_OFFER = new AliasOffer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AliasOfferRecord> getRecordType() {
        return AliasOfferRecord.class;
    }

    /**
     * The column <code>DB.alias_offer.db_id</code>.
     */
    public final TableField<AliasOfferRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.alias_offer.id</code>.
     */
    public final TableField<AliasOfferRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.alias_offer.price</code>.
     */
    public final TableField<AliasOfferRecord, Long> PRICE = createField(DSL.name("price"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.alias_offer.buyer_id</code>.
     */
    public final TableField<AliasOfferRecord, Long> BUYER_ID = createField(DSL.name("buyer_id"), SQLDataType.BIGINT.defaultValue(DSL.field("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>DB.alias_offer.height</code>.
     */
    public final TableField<AliasOfferRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.alias_offer.latest</code>.
     */
    public final TableField<AliasOfferRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private AliasOffer(Name alias, Table<AliasOfferRecord> aliased) {
        this(alias, aliased, null);
    }

    private AliasOffer(Name alias, Table<AliasOfferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.alias_offer</code> table reference
     */
    public AliasOffer(String alias) {
        this(DSL.name(alias), ALIAS_OFFER);
    }

    /**
     * Create an aliased <code>DB.alias_offer</code> table reference
     */
    public AliasOffer(Name alias) {
        this(alias, ALIAS_OFFER);
    }

    /**
     * Create a <code>DB.alias_offer</code> table reference
     */
    public AliasOffer() {
        this(DSL.name("alias_offer"), null);
    }

    public <O extends Record> AliasOffer(Table<O> child, ForeignKey<O, AliasOfferRecord> key) {
        super(child, key, ALIAS_OFFER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public Identity<AliasOfferRecord, Long> getIdentity() {
        return (Identity<AliasOfferRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AliasOfferRecord> getPrimaryKey() {
        return Keys.KEY_ALIAS_OFFER_PRIMARY;
    }

    @Override
    public List<UniqueKey<AliasOfferRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ALIAS_OFFER_ALIAS_OFFER_ID_HEIGHT_IDX);
    }

    @Override
    public AliasOffer as(String alias) {
        return new AliasOffer(DSL.name(alias), this);
    }

    @Override
    public AliasOffer as(Name alias) {
        return new AliasOffer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AliasOffer rename(String name) {
        return new AliasOffer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AliasOffer rename(Name name) {
        return new AliasOffer(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
