/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Indexes;
import brs.schema.Keys;
import brs.schema.tables.records.AskOrderRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AskOrder extends TableImpl<AskOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.ask_order</code>
     */
    public static final AskOrder ASK_ORDER = new AskOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AskOrderRecord> getRecordType() {
        return AskOrderRecord.class;
    }

    /**
     * The column <code>DB.ask_order.db_id</code>.
     */
    public final TableField<AskOrderRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.ask_order.id</code>.
     */
    public final TableField<AskOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.account_id</code>.
     */
    public final TableField<AskOrderRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.asset_id</code>.
     */
    public final TableField<AskOrderRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.price</code>.
     */
    public final TableField<AskOrderRecord, Long> PRICE = createField(DSL.name("price"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.quantity</code>.
     */
    public final TableField<AskOrderRecord, Long> QUANTITY = createField(DSL.name("quantity"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.creation_height</code>.
     */
    public final TableField<AskOrderRecord, Integer> CREATION_HEIGHT = createField(DSL.name("creation_height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.height</code>.
     */
    public final TableField<AskOrderRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.ask_order.latest</code>.
     */
    public final TableField<AskOrderRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private AskOrder(Name alias, Table<AskOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private AskOrder(Name alias, Table<AskOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.ask_order</code> table reference
     */
    public AskOrder(String alias) {
        this(DSL.name(alias), ASK_ORDER);
    }

    /**
     * Create an aliased <code>DB.ask_order</code> table reference
     */
    public AskOrder(Name alias) {
        this(alias, ASK_ORDER);
    }

    /**
     * Create a <code>DB.ask_order</code> table reference
     */
    public AskOrder() {
        this(DSL.name("ask_order"), null);
    }

    public <O extends Record> AskOrder(Table<O> child, ForeignKey<O, AskOrderRecord> key) {
        super(child, key, ASK_ORDER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ASK_ORDER_ASK_ORDER_ACCOUNT_ID_IDX, Indexes.ASK_ORDER_ASK_ORDER_ASSET_ID_PRICE_IDX, Indexes.ASK_ORDER_ASK_ORDER_CREATION_IDX);
    }

    @Override
    public Identity<AskOrderRecord, Long> getIdentity() {
        return (Identity<AskOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AskOrderRecord> getPrimaryKey() {
        return Keys.KEY_ASK_ORDER_PRIMARY;
    }

    @Override
    public List<UniqueKey<AskOrderRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ASK_ORDER_ASK_ORDER_ID_HEIGHT_IDX);
    }

    @Override
    public AskOrder as(String alias) {
        return new AskOrder(DSL.name(alias), this);
    }

    @Override
    public AskOrder as(Name alias) {
        return new AskOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AskOrder rename(String name) {
        return new AskOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AskOrder rename(Name name) {
        return new AskOrder(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, Long, Long, Integer, Integer, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
