/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Keys;
import brs.schema.tables.records.AtMapRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtMap extends TableImpl<AtMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.at_map</code>
     */
    public static final AtMap AT_MAP = new AtMap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtMapRecord> getRecordType() {
        return AtMapRecord.class;
    }

    /**
     * The column <code>DB.at_map.db_id</code>.
     */
    public final TableField<AtMapRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.at_map.at_id</code>.
     */
    public final TableField<AtMapRecord, Long> AT_ID = createField(DSL.name("at_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.at_map.key1</code>.
     */
    public final TableField<AtMapRecord, Long> KEY1 = createField(DSL.name("key1"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.at_map.key2</code>.
     */
    public final TableField<AtMapRecord, Long> KEY2 = createField(DSL.name("key2"), SQLDataType.BIGINT.defaultValue(DSL.field("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>DB.at_map.value</code>.
     */
    public final TableField<AtMapRecord, Long> VALUE = createField(DSL.name("value"), SQLDataType.BIGINT.defaultValue(DSL.field("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>DB.at_map.height</code>.
     */
    public final TableField<AtMapRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.at_map.latest</code>.
     */
    public final TableField<AtMapRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private AtMap(Name alias, Table<AtMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private AtMap(Name alias, Table<AtMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.at_map</code> table reference
     */
    public AtMap(String alias) {
        this(DSL.name(alias), AT_MAP);
    }

    /**
     * Create an aliased <code>DB.at_map</code> table reference
     */
    public AtMap(Name alias) {
        this(alias, AT_MAP);
    }

    /**
     * Create a <code>DB.at_map</code> table reference
     */
    public AtMap() {
        this(DSL.name("at_map"), null);
    }

    public <O extends Record> AtMap(Table<O> child, ForeignKey<O, AtMapRecord> key) {
        super(child, key, AT_MAP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public Identity<AtMapRecord, Long> getIdentity() {
        return (Identity<AtMapRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AtMapRecord> getPrimaryKey() {
        return Keys.KEY_AT_MAP_PRIMARY;
    }

    @Override
    public AtMap as(String alias) {
        return new AtMap(DSL.name(alias), this);
    }

    @Override
    public AtMap as(Name alias) {
        return new AtMap(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtMap rename(String name) {
        return new AtMap(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtMap rename(Name name) {
        return new AtMap(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
