/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Indexes;
import brs.schema.Keys;
import brs.schema.tables.records.AtStateRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtState extends TableImpl<AtStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.at_state</code>
     */
    public static final AtState AT_STATE = new AtState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtStateRecord> getRecordType() {
        return AtStateRecord.class;
    }

    /**
     * The column <code>DB.at_state.db_id</code>.
     */
    public final TableField<AtStateRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.at_state.at_id</code>.
     */
    public final TableField<AtStateRecord, Long> AT_ID = createField(DSL.name("at_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.state</code>.
     */
    public final TableField<AtStateRecord, byte[]> STATE = createField(DSL.name("state"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.prev_height</code>.
     */
    public final TableField<AtStateRecord, Integer> PREV_HEIGHT = createField(DSL.name("prev_height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.next_height</code>.
     */
    public final TableField<AtStateRecord, Integer> NEXT_HEIGHT = createField(DSL.name("next_height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.sleep_between</code>.
     */
    public final TableField<AtStateRecord, Integer> SLEEP_BETWEEN = createField(DSL.name("sleep_between"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.prev_balance</code>.
     */
    public final TableField<AtStateRecord, Long> PREV_BALANCE = createField(DSL.name("prev_balance"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.freeze_when_same_balance</code>.
     */
    public final TableField<AtStateRecord, Boolean> FREEZE_WHEN_SAME_BALANCE = createField(DSL.name("freeze_when_same_balance"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.min_activate_amount</code>.
     */
    public final TableField<AtStateRecord, Long> MIN_ACTIVATE_AMOUNT = createField(DSL.name("min_activate_amount"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.height</code>.
     */
    public final TableField<AtStateRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.at_state.latest</code>.
     */
    public final TableField<AtStateRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private AtState(Name alias, Table<AtStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private AtState(Name alias, Table<AtStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.at_state</code> table reference
     */
    public AtState(String alias) {
        this(DSL.name(alias), AT_STATE);
    }

    /**
     * Create an aliased <code>DB.at_state</code> table reference
     */
    public AtState(Name alias) {
        this(alias, AT_STATE);
    }

    /**
     * Create a <code>DB.at_state</code> table reference
     */
    public AtState() {
        this(DSL.name("at_state"), null);
    }

    public <O extends Record> AtState(Table<O> child, ForeignKey<O, AtStateRecord> key) {
        super(child, key, AT_STATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AT_STATE_AT_STATE_ID_NEXT_HEIGHT_HEIGHT_IDX);
    }

    @Override
    public Identity<AtStateRecord, Long> getIdentity() {
        return (Identity<AtStateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AtStateRecord> getPrimaryKey() {
        return Keys.KEY_AT_STATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<AtStateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AT_STATE_AT_STATE_AT_ID_HEIGHT_IDX);
    }

    @Override
    public AtState as(String alias) {
        return new AtState(DSL.name(alias), this);
    }

    @Override
    public AtState as(Name alias) {
        return new AtState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtState rename(String name) {
        return new AtState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtState rename(Name name) {
        return new AtState(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, byte[], Integer, Integer, Integer, Long, Boolean, Long, Integer, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
