/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Indexes;
import brs.schema.Keys;
import brs.schema.tables.records.EscrowDecisionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EscrowDecision extends TableImpl<EscrowDecisionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.escrow_decision</code>
     */
    public static final EscrowDecision ESCROW_DECISION = new EscrowDecision();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EscrowDecisionRecord> getRecordType() {
        return EscrowDecisionRecord.class;
    }

    /**
     * The column <code>DB.escrow_decision.db_id</code>.
     */
    public final TableField<EscrowDecisionRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.escrow_decision.escrow_id</code>.
     */
    public final TableField<EscrowDecisionRecord, Long> ESCROW_ID = createField(DSL.name("escrow_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.escrow_decision.account_id</code>.
     */
    public final TableField<EscrowDecisionRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.escrow_decision.decision</code>.
     */
    public final TableField<EscrowDecisionRecord, Integer> DECISION = createField(DSL.name("decision"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.escrow_decision.height</code>.
     */
    public final TableField<EscrowDecisionRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.escrow_decision.latest</code>.
     */
    public final TableField<EscrowDecisionRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private EscrowDecision(Name alias, Table<EscrowDecisionRecord> aliased) {
        this(alias, aliased, null);
    }

    private EscrowDecision(Name alias, Table<EscrowDecisionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.escrow_decision</code> table reference
     */
    public EscrowDecision(String alias) {
        this(DSL.name(alias), ESCROW_DECISION);
    }

    /**
     * Create an aliased <code>DB.escrow_decision</code> table reference
     */
    public EscrowDecision(Name alias) {
        this(alias, ESCROW_DECISION);
    }

    /**
     * Create a <code>DB.escrow_decision</code> table reference
     */
    public EscrowDecision() {
        this(DSL.name("escrow_decision"), null);
    }

    public <O extends Record> EscrowDecision(Table<O> child, ForeignKey<O, EscrowDecisionRecord> key) {
        super(child, key, ESCROW_DECISION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ESCROW_DECISION_ESCROW_DECISION_ACCOUNT_ID_HEIGHT_IDX, Indexes.ESCROW_DECISION_ESCROW_DECISION_ESCROW_ID_HEIGHT_IDX);
    }

    @Override
    public Identity<EscrowDecisionRecord, Long> getIdentity() {
        return (Identity<EscrowDecisionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EscrowDecisionRecord> getPrimaryKey() {
        return Keys.KEY_ESCROW_DECISION_PRIMARY;
    }

    @Override
    public List<UniqueKey<EscrowDecisionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ESCROW_DECISION_ESCROW_DECISION_ESCROW_ID_ACCOUNT_ID_HEIGHT_IDX);
    }

    @Override
    public EscrowDecision as(String alias) {
        return new EscrowDecision(DSL.name(alias), this);
    }

    @Override
    public EscrowDecision as(Name alias) {
        return new EscrowDecision(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EscrowDecision rename(String name) {
        return new EscrowDecision(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EscrowDecision rename(Name name) {
        return new EscrowDecision(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Integer, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
