/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Indexes;
import brs.schema.Keys;
import brs.schema.tables.records.RewardRecipAssignRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RewardRecipAssign extends TableImpl<RewardRecipAssignRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.reward_recip_assign</code>
     */
    public static final RewardRecipAssign REWARD_RECIP_ASSIGN = new RewardRecipAssign();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RewardRecipAssignRecord> getRecordType() {
        return RewardRecipAssignRecord.class;
    }

    /**
     * The column <code>DB.reward_recip_assign.db_id</code>.
     */
    public final TableField<RewardRecipAssignRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.reward_recip_assign.account_id</code>.
     */
    public final TableField<RewardRecipAssignRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.reward_recip_assign.prev_recip_id</code>.
     */
    public final TableField<RewardRecipAssignRecord, Long> PREV_RECIP_ID = createField(DSL.name("prev_recip_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.reward_recip_assign.recip_id</code>.
     */
    public final TableField<RewardRecipAssignRecord, Long> RECIP_ID = createField(DSL.name("recip_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.reward_recip_assign.from_height</code>.
     */
    public final TableField<RewardRecipAssignRecord, Integer> FROM_HEIGHT = createField(DSL.name("from_height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.reward_recip_assign.height</code>.
     */
    public final TableField<RewardRecipAssignRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.reward_recip_assign.latest</code>.
     */
    public final TableField<RewardRecipAssignRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private RewardRecipAssign(Name alias, Table<RewardRecipAssignRecord> aliased) {
        this(alias, aliased, null);
    }

    private RewardRecipAssign(Name alias, Table<RewardRecipAssignRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.reward_recip_assign</code> table reference
     */
    public RewardRecipAssign(String alias) {
        this(DSL.name(alias), REWARD_RECIP_ASSIGN);
    }

    /**
     * Create an aliased <code>DB.reward_recip_assign</code> table reference
     */
    public RewardRecipAssign(Name alias) {
        this(alias, REWARD_RECIP_ASSIGN);
    }

    /**
     * Create a <code>DB.reward_recip_assign</code> table reference
     */
    public RewardRecipAssign() {
        this(DSL.name("reward_recip_assign"), null);
    }

    public <O extends Record> RewardRecipAssign(Table<O> child, ForeignKey<O, RewardRecipAssignRecord> key) {
        super(child, key, REWARD_RECIP_ASSIGN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.REWARD_RECIP_ASSIGN_REWARD_RECIP_ASSIGN_RECIP_ID_HEIGHT_IDX);
    }

    @Override
    public Identity<RewardRecipAssignRecord, Long> getIdentity() {
        return (Identity<RewardRecipAssignRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RewardRecipAssignRecord> getPrimaryKey() {
        return Keys.KEY_REWARD_RECIP_ASSIGN_PRIMARY;
    }

    @Override
    public List<UniqueKey<RewardRecipAssignRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_REWARD_RECIP_ASSIGN_REWARD_RECIP_ASSIGN_ACCOUNT_ID_HEIGHT_IDX);
    }

    @Override
    public RewardRecipAssign as(String alias) {
        return new RewardRecipAssign(DSL.name(alias), this);
    }

    @Override
    public RewardRecipAssign as(Name alias) {
        return new RewardRecipAssign(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RewardRecipAssign rename(String name) {
        return new RewardRecipAssign(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RewardRecipAssign rename(Name name) {
        return new RewardRecipAssign(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Integer, Integer, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
